name: 'Install Atlas SDK'
runs:
  using: "composite"
  steps: 
    - id: Add Atlassian SDK repositories
      run: sudo sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >>/etc/apt/sources.list'
      shell: bash
    - id: Download Public GPG key
      run: wget https://packages.atlassian.com/api/gpg/key/public
      shell: bash
    - id: Add Public GPG key
      run: sudo apt-key add public
      shell: bash
    - id: Install Atlassian Atlas SDK
      run: sudo apt-get install atlassian-plugin-sdk
      shell: bash
